# Generated by Django 5.0.4 on 2024-05-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srtuser',
            name='korailID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='srtuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
