# Generated by Django 5.0.4 on 2024-07-02 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MecroMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mecro_id', models.CharField(max_length=200)),
                ('korailID', models.CharField(blank=True, max_length=50, null=True)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('dep', models.CharField(max_length=200)),
                ('arr', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('dep_time_from', models.CharField(max_length=200)),
                ('dep_time_to', models.CharField(max_length=200)),
                ('available_only', models.CharField(max_length=10)),
                ('first_seat_YN', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mecro_case', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
