# Generated by Django 5.0.4 on 2024-07-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mecromaster',
            name='available_only',
        ),
        migrations.AlterField(
            model_name='mecromaster',
            name='korailID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mecromaster',
            name='time_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mecromaster',
            name='time_out',
            field=models.DateTimeField(null=True),
        ),
    ]
