# Generated by Django 5.0.4 on 2024-07-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srt', '0002_remove_mecromaster_available_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecromaster',
            name='task_ID',
            field=models.CharField(default='0000000', max_length=200),
        ),
    ]
