# Generated by Django 5.0.4 on 2024-07-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srt', '0003_mecromaster_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mecromaster',
            old_name='user',
            new_name='client',
        ),
    ]
